on: [push, pull_request]

jobs:
    compile:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                cl test.c
                test
