on: [push, pull_request]

jobs:
    deployment_keys_demo:
        env:
            GIT_SSH_COMMAND: ssh -v
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup key
              uses: ./
              with:
                  ssh-private-key: |
                    ${{ secrets.MPDUDE_TEST_1_DEPLOY_KEY }}
                    ${{ secrets.MPDUDE_TEST_2_DEPLOY_KEY }}
#            - run: |
#                cat ~/.ssh/config                
#                ssh-add -l
#                C:/Windows/System32/OpenSSH/ssh.exe -v git@key-2 'echo octocat'
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
              
#                git clone git@github.com:mpdude/test-2.git test-2-git
#                ls -alh ~/.ssh
#                git clone https://github.com/mpdude/test-1.git test-1-http
#                git clone git@github.com:mpdude/test-1.git test-1-git
#                git clone ssh://git@github.com/mpdude/test-1.git test-1-git-ssh
#                git clone https://github.com/mpdude/test-2.git test-2-http

#                git clone ssh://git@github.com/mpdude/test-2.git test-2-git-ssh
                
#                cat > ~/.ssh/5965bf89ab6e2900262e3f6802dfb4d65cb0de539d0fbb97d381e7130a4ba7e9 <<< "${{ secrets.MPDUDE_TEST_2_DEPLOY_KEY }}"
#                ssh-keygen -p -f ~/.ssh/5965bf89ab6e2900262e3f6802dfb4d65cb0de539d0fbb97d381e7130a4ba7e9 -N secret-passphrase
#                eval `ssh-agent`
#                echo "secret-passphrase" | ssh-add ~/.ssh/5965bf89ab6e2900262e3f6802dfb4d65cb0de539d0fbb97d381e7130a4ba7e9
#                ssh-add -L
#                git clone git@github.com:mpdude/test-2.git test-2-git
#              shell: bash
