on: [push, pull_request]

jobs:
    single_key_demo:
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup key
              uses: ./
              with:
                  ssh-private-key: |
                    ${{ secrets.DEMO_KEY }}
                    ${{ secrets.DEMO_KEY_2 }}

    multiple_keys_demo:
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup key
              uses: ./
              with:
                  ssh-private-key: ${{ secrets.DEMO_KEY }}

    docker_demo:
        runs-on: ubuntu-latest        
        container:
            image: ubuntu:latest
        steps:
            - uses: actions/checkout@v2
            - run: apt update && apt install -y openssh-client
            - name: Setup key
              uses: ./
              with:
                  ssh-private-key: |
                    ${{ secrets.DEMO_KEY }}
                    ${{ secrets.DEMO_KEY_2 }}

    deployment_keys_demo:
        env:
            GIT_SSH_COMMAND: ssh -v
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup key
              uses: ./
              with:
                  ssh-private-key: |
                    ${{ secrets.MPDUDE_TEST_1_DEPLOY_KEY }}
                    ${{ secrets.MPDUDE_TEST_2_DEPLOY_KEY }}
            - run: |
                cat > ~/.ssh/5965bf89ab6e2900262e3f6802dfb4d65cb0de539d0fbb97d381e7130a4ba7e9 <<< "${{ secrets.MPDUDE_TEST_2_DEPLOY_KEY }}"
                ssh-keygen -p -f ~/.ssh/5965bf89ab6e2900262e3f6802dfb4d65cb0de539d0fbb97d381e7130a4ba7e9 -N secret-passphrase
                echo "secret-passphrase" | ssh-add ~/.ssh/5965bf89ab6e2900262e3f6802dfb4d65cb0de539d0fbb97d381e7130a4ba7e9
                git clone git@github.com:mpdude/test-2.git test-2-git
              shell: bash
